### ISSUE TITLE
Decryption Help

### ISSUE THREAD

**Issue by mrevjd** [PVermeer/dexie-addon-suite-monorepo#2]
Hi team,
Great addon. thanks!
I'm just trying to understand how to decrypt the data on reading.
I have been suing your html example and can see the data is encrypted
Thanks

**Comment by PVermeer** [comment]
Hi there,

You should not have to encrypt / decrypt data yourself. It saves data encrypted in the Dexie database and encrypt it on reading. I've made a test example and it seems to work fine:

[StackBlitz expamle](https://stackblitz.com/edit/web-platform-xqrudi?file=script.js)

If its not working for you please provide an example or fork and edit the StackBlitz to your setup.

I did notice an error in the HTML example concerning the namespace of the Encrypted class. This will be corrected.
Fixed with commit 620651a8e4ebb542d2ccbd6c230372936063037e

**Comment by mrevjd** [comment]
Thank you for such a speedy response. 
I will try your example and let you know.

**Comment by mrevjd** [comment]
@PVermeer 
I know where I went wrong by using your example.
Thank you once again.
